export const ENDPOINTS = {
  AUTH_LOGIN: '/auth/login',
  AUTH_ME: '/auth/me',
  AUTH_PROFILE: '/auth/profile',
  AUTH_PROFILE_PHOTO: '/auth/profile/photo',
  AUTH_DELETE_PROFILE_PHOTO: '/auth/profile/photo',
  REVIEWS_CLEANER: '/reviews/cleaner',
  CLEANERS_KYC: '/admin/cleaners/kyc',
  CLEANERS_KYC_STATS: '/admin/cleaners/kyc/stats',
  CLEANERS: '/admin/cleaners',
  CLEANER_ABN_VERIFY: '/admin/cleaners',
  CUSTOMERS: '/admin/customers',
  CUSTOMERS_JOBS_STATS: '/admin/jobs/stats/customers',
  CLEANERS_JOBS_STATS: '/admin/jobs/stats/cleaners',
  RECENT_ACTIVITY: '/admin/recent-activity',
  TOP_LOCATIONS: '/admin/jobs/top-locations',
  JOBS: '/admin/jobs',
  UPDATE_PAYMENT_STATUS: '/admin/jobs',
  REVIEWS: '/reviews',
  ADMIN_USERS: '/admin/users',
  REVENUE_MTD: '/revenue/mtd',
  SUBSCRIPTION_REPORT: '/admin/subscriptions/report',
  CLEANER_PAYMENTS: '/admin/cleaners',
  FAQ_CATEGORIES: '/admin/faq-categories',
  FAQS: '/admin/faqs',
};
